DROP TABLE IF EXISTS  `sessions`;

CREATE TABLE  IF NOT EXISTS `sessions` (
  id VARCHAR(32) NOT NULL,
  data TEXT NOT NULL,
  `LastVisit` DATETIME on update CURRENT_TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);